<div class="submenu2">
<a href="#tables">Tables</a>
<a href="#chairs">Chairs</a>
<a href="#dance">Dance Floors &amp; Bars</a>
<a href="#lighting">Lighting</a>
<a href="#pole">Pole Wraps & Swags</a>
<a href="#climate">Climate Control</a>
<a href="#linens">Linens</a>
<a href="#bartenders">Staffing</a></div>
